### ISSUE TITLE
Wrong return value for certain item types

### ISSUE THREAD

**Issue by FreezeSpell** [OlivierBroekman/rust-raid-cost-calculator#25]
When either Vehicle or Building type is selected as item type in the options, the name of the item in the output box is returned as "Not a valid item name or ID.". Suspected issue with pythonFunctions.py and functions.py

Deployable type does work properly and returns the input item as name.

**Comment by OlivierBroekman** [comment]
Should be fixed now.
EDIT: Both in functions.py and pythonFunctions.py
