### ISSUE TITLE
Background weird

### ISSUE THREAD

**Issue by FreezeSpell** [OlivierBroekman/rust-raid-cost-calculator#28]
The background image does not stretch properly (read: at all), must be a CSS issue. Quickly solved, but don't feel like doing it now.

**Comment by OlivierBroekman** [comment]
Maybe first choose different background before fixing this (I do not know if this is an inherent issue to all backgrounds or this background specifically though)

**Comment by FreezeSpell** [comment]
Is an inherent issue for all backgrounds

**Comment by FreezeSpell** [comment]
Functional now
