### ISSUE TITLE
calculator issue

### ISSUE THREAD

**Issue by FreezeSpell** [OlivierBroekman/rust-raid-cost-calculator#41]
calculator does not take into account that homing missiles can only be used on airborne vehicles

steps to reproduce:
exploraid & deployable
item name: Above Ground Pool

most efficient way is homing missile, but that can't work

**Comment by OlivierBroekman** [comment]
Correct me if I'm wrong on this, but I'm quite sure you can fire a homing missile without locking onto a mini/scrappy/attack heli.

**Comment by FreezeSpell** [comment]
Just tried, you need to be locked onto a airborne vehicle

**Comment by OlivierBroekman** [comment]
Fixed.
